### ISSUE TITLE
on Fragment

### ISSUE THREAD

**Issue by anangpmb** [mikepenz/Android-ActionItemBadge#31]
I have a trouble use this library on Fragment...
onClick item not work on Fragment

**Comment by mikepenz** [comment]
@anangpmb can you be a bit more specific? you can only handle the menu via the activity. you can pass over the infos to the fragment. but in general everything happens in the activity

**Comment by anangpmb** [comment]
I have chart icon on actionbar and I have to use badge on every activity, but I have fragment too that it has to use badge and cart icon too.. can I handle on mainActivity but show on every fragment?

**Comment by mikepenz** [comment]
yes you can. be careful and don't mix up fragments and activities and what they contain. i am sure you will find how to do this on stackOverFlow or google. nothing specific to this lib

**Comment by WonderCsabo** [comment]
I also have this problem. The menu is created by the Fragment and the item selection events are handled by the Fragment. The Activity actually has nothing to do with this.

Now my Activity is getting the callback instead of the Fragment. What about providing an override which accepts Fragment instead of Activity?

**Comment by mikepenz** [comment]
@WonderCsabo probably you open a new issue for this

**Comment by WonderCsabo** [comment]
See #36.
