### ISSUE TITLE
Same questions

### ISSUE THREAD

**Issue by AlexeyKorshun** [mikepenz/Android-ActionItemBadge#47]
Good day. Thx for library.
I have 3 question.

Why I can't use this library without com.mikepenz:iconics?

Can you create BadgeStyle with circle?

Method 'hide' hide my item too. How can I hide only badge?

**Comment by mikepenz** [comment]
@AlexeyKorshun because the library comes with built in easy support for the `Android-Iconics` library. (which is a huge advantage for many users. It only uses the `iconics-core` which is really slim though)

Yes you can as you can provide a `corner` so just set the corner radius to the half of the badge-size

You can have an if here: https://github.com/mikepenz/Android-ActionItemBadge/blob/develop/README.md#activity and if your count is 0 you just remove the badged one and set a normal menu item

**Comment by AlexeyKorshun** [comment]
Bih thx, but when I must provide `corner` ?

**Comment by mikepenz** [comment]
@AlexeyKorshun https://github.com/mikepenz/Android-ActionItemBadge/blob/48d18dcd6b0f3e1a23a215c85aec5a5488aaef92/library/src/main/java/com/mikepenz/actionitembadge/library/utils/BadgeStyle.java#L80

You can just provide any `BadgeStyle` (predefined or initialized by you) to the update method

**Comment by zulkarnainshah** [comment]
How to get **badge-size** ?

**Comment by mikepenz** [comment]
@zulkarnainshah this layout is used, so it is not defined. it depends on the font size: https://github.com/mikepenz/Android-ActionItemBadge/blob/develop/library/src/main/res/layout/menu_action_item_badge.xml#L16

**Comment by zulkarnainshah** [comment]
So how exactly would i create a circular badge?

**Comment by mikepenz** [comment]
@AlexeyKorshun you can overwrite this item, define a fixed dp height, and set a corner which is exactly half of the height

**Comment by technoplusplus** [comment]
I'm new to your library .. i need to know how to change the size of badge ! the budge is located on toolbar action menu item

**Comment by ghost** [comment]
i can't edit fun setCorner in library
